more

diff --git a/common/Makefile b/common/Makefile
--- a/common/Makefile
+++ b/common/Makefile
@@ -46,11 +46,14 @@ show: ## show the starting template without installing it
 
 .PHONY: operator-deploy
 operator-deploy operator-upgrade: validate-prereq validate-origin ## runs helm install
-	@set -ex
+	@set -ex -o pipefail
 	echo "Reapplying helm chart:"
 	# We reapply the CRD and if it already exists we do not error out
 	oc apply common/operator-install/crds/*.yaml 2>/dev/null || /bin/true
-	helm template --name-template $(NAME) common/operator-install/ $(HELM_OPTS) | oc apply -f-
+	# Retry five times because the CRD might not be fully installed yet
+	for i in {1..5}; do \
+		helm template --name-template $(NAME) common/operator-install/ $(HELM_OPTS) | oc apply -f- && break || sleep 5; \
+	done
 
 .PHONY: uninstall
 uninstall: ## runs helm uninstall
